# Generated by Django 3.2.16 on 2023-01-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=280)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=280)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-date_start',),
            },
        ),
    ]
