# Generated by Django 3.2.16 on 2023-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='website_name',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
